/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.68
 * Generated at: 2022-10-23 05:25:12 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class addProduct_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"ko\">\n");
      out.write("<head>\n");
      out.write("	<meta charset=\"UTF-8\">\n");
      out.write("	<title>MLB-Statcast Database</title>\n");
      out.write("	<link rel=\"stylesheet\" type=\"text/css\" href=\"../xeicon/xeicon.min.css\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"css_part/geton.css\">\n");
      out.write("	<link rel=\"stylesheet\" href=\"css_part/swiper.min.css\">\n");
      out.write("	<link rel=\"stylesheet\" href=\"css_part/default.css\">\n");
      out.write("	<script src=\"script_part/jquery.js\" charset=\"utf-8\"></script>\n");
      out.write("	<script src=\"script_part/swiper.js\" charset=\"utf-8\"></script>\n");
      out.write("	<script src=\"script_part/default.js\" charset=\"utf-8\"></script>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "Top.jsp", out, false);
      out.write("\n");
      out.write("    <main>\n");
      out.write("        <section class=\"block\">\n");
      out.write("       <form name=\"newProduct\" action=\"./processAddProduct.jsp\" method = \"post\">\n");
      out.write("            <div class=\"joincontents\">\n");
      out.write("                <h2 class=\"subject2\">등록하기</h2>\n");
      out.write("               \n");
      out.write("                <div class=\"join_box2\">\n");
      out.write("                    <h3 class=\"subject3\">피규어 등록하기</h3>\n");
      out.write("\n");
      out.write("                    <table class=\"type1\">\n");
      out.write("                        <caption></caption>\n");
      out.write("                        <colgroup>\n");
      out.write("                            <col style=\"width:170px;\">\n");
      out.write("                            <col>\n");
      out.write("                        </colgroup>\n");
      out.write("                        <tbody>\n");
      out.write("                            <tr>\n");
      out.write("                                <th><span>필수입력</span>상품명</th>\n");
      out.write("                                <td>\n");
      out.write("                                    <input type=\"text\" name=\"pname\" style=\"width:150px;\">\n");
      out.write("                               \n");
      out.write("                                </td>\n");
      out.write("\n");
      out.write("                            </tr>\n");
      out.write("                            <tr>\n");
      out.write("                                <th><span>필수입력</span>상품 영어명</th>\n");
      out.write("                                <td>\n");
      out.write("                                    <input type=\"text\" name=\"pename\" style=\"width:150px;\">\n");
      out.write("                          \n");
      out.write("                                </td>\n");
      out.write("\n");
      out.write("                            </tr>\n");
      out.write("                            <tr>\n");
      out.write("                                <th><span>필수입력</span>판매가</th>\n");
      out.write("                                <td>\n");
      out.write("                                    <input type=\"text\" style=\"width:150px;\" name=\"unitprice\">\n");
      out.write("                                    <span class=\"ifo\">숫자 단위까지 모두 입력하세요</span>\n");
      out.write("                                </td>\n");
      out.write("\n");
      out.write("                            </tr>\n");
      out.write("                            <tr>\n");
      out.write("                                <th><span>필수입력</span>상품코드</th>\n");
      out.write("                                <td><input type=\"text\" style=\"width:150px;\" name=\"pcode\">\n");
      out.write("                                    <span class=\"ifo\">상품코드는 이메일을 확인해주세요.</span> \n");
      out.write("                                </td>\n");
      out.write("                               \n");
      out.write("\n");
      out.write("                            </tr>\n");
      out.write("                            <tr>\n");
      out.write("                                <th><span>필수입력</span>제조사 및 공급사</th>\n");
      out.write("                                <td><input type=\"text\" style=\"width:150px;\" name=\"man\"></td>\n");
      out.write("\n");
      out.write("                            </tr>\n");
      out.write("                            <tr>\n");
      out.write("                                <th><span>필수입력</span>쿠폰사용갯수</th>\n");
      out.write("                                <td><input type=\"text\" style=\"width:150px;\" name=\"unitcoupon\"></td>\n");
      out.write("\n");
      out.write("                            </tr>\n");
      out.write("                        </tbody>\n");
      out.write("                    </table>\n");
      out.write("\n");
      out.write("\n");
      out.write("                <div class=\"btn_center\">\n");
      out.write("                    <input type=\"submit\" value=\"등록하기\" class=\"btn_type1\">\n");
      out.write("                    <a href=\"\" class=\"btn_type2\">취소 </a>\n");
      out.write("                </div>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("            </div>\n");
      out.write("           </form>\n");
      out.write("        </section>\n");
      out.write("    </main>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
